url: https://apsa.github.io
baseurl:

# Site settings
title: APSA
email: berkeleyapsa@gmail.com
description:

# Team names, titles and social links
people:
- name: Masha Bondarenko
  pic: 1
  position: President
  year: Senior - Electrical Engineering & Computer Science

- name: Nicole Klatt
  pic: Nicole #8
  position: Internal Vice President
  year: Sophomore - MCB (Emphasis: Immunology) + Data Science

- name: Mikayla Bordador
  pic: 7
  position: External Vice President
  year: Sophomore - Human Integrative Biology + Public Health + Music

- name: Lavanya Gupta
  pic: 2
  position: Academic Chair
  year: Senior - MCB (Emphasis: Immunology)

- name: Kate Yang
  pic: 3
  position: Professional Development Chair
  year: Freshman - Public Health

- name: Isa Vivona
  pic: 4
  position: Social Media Chair
  year: Sophomore - MCB (Emphasis: Immunology) + Public Health

- name: Humayd Zameer
  pic: Humayd #8
  position: Secretary
  year: Sophomore - MCB (Emphasis: Neurobiology)

- name: Ronit Nath
  pic: 8
  position: Technology Chair
  year: Senior - Philosophy + Computer Science

- name: Rableen Singh Ghuman
  pic: Rableen #8
  position: Technology Chair
  year: Freshman - Neuroscience

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/berkeleyapsa/?hl=en
  - title: facebook
    url: https://www.facebook.com/berkeleyapsa
  - title: google-plus
    url: mailto:berkeleyapsa@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: University of California, Berkeley
  - line: Berkeley, CA 94704

# Build settings
markdown: kramdown
permalink: pretty
